kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE_USERNAME-read-only
  namespace: NAMESPACE_NAME
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get","watch","list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get","watch","list"]